package au.gov.nsw.records.digitalarchive.ORM;


import java.util.HashSet;
import java.util.Set;

/**
 * FullAgencyList generated by hbm2java
 */
public class FullAgencyList implements java.io.Serializable {

	private Integer fullAgencyListId;
	private Integer bosId;
	private Integer tempId;
	private String agencyName;
	private Set<PublisherPublication> publisherPublications = new HashSet<PublisherPublication>(
			0);
	private Set<AgencyPublication> agencyPublications = new HashSet<AgencyPublication>(
			0);
	private Set<Member> members = new HashSet<Member>(0);

	public FullAgencyList() {
	}

	public FullAgencyList(Integer bosId, Integer tempId, String agencyName,
			Set<PublisherPublication> publisherPublications,
			Set<AgencyPublication> agencyPublications, Set<Member> members) {
		this.bosId = bosId;
		this.tempId = tempId;
		this.agencyName = agencyName;
		this.publisherPublications = publisherPublications;
		this.agencyPublications = agencyPublications;
		this.members = members;
	}

	public Integer getFullAgencyListId() {
		return this.fullAgencyListId;
	}

	public void setFullAgencyListId(Integer fullAgencyListId) {
		this.fullAgencyListId = fullAgencyListId;
	}

	public Integer getBosId() {
		return this.bosId;
	}

	public void setBosId(Integer bosId) {
		this.bosId = bosId;
	}

	public Integer getTempId() {
		return this.tempId;
	}

	public void setTempId(Integer tempId) {
		this.tempId = tempId;
	}

	public String getAgencyName() {
		return this.agencyName;
	}

	public void setAgencyName(String agencyName) {
		this.agencyName = agencyName;
	}

	public Set<PublisherPublication> getPublisherPublications() {
		return this.publisherPublications;
	}

	public void setPublisherPublications(
			Set<PublisherPublication> publisherPublications) {
		this.publisherPublications = publisherPublications;
	}

	public Set<AgencyPublication> getAgencyPublications() {
		return this.agencyPublications;
	}

	public void setAgencyPublications(Set<AgencyPublication> agencyPublications) {
		this.agencyPublications = agencyPublications;
	}

	public Set<Member> getMembers() {
		return this.members;
	}

	public void setMembers(Set<Member> members) {
		this.members = members;
	}

}
