package au.gov.nsw.records.digitalarchive.ORM;


import java.util.HashSet;
import java.util.Set;

/**
 * BosList generated by hbm2java
 */
public class BosList implements java.io.Serializable {

	private int agencyNumber;
	private String agencyName;
	private Set<Agency> agencies = new HashSet<Agency>(0);

	public BosList() {
	}

	public BosList(int agencyNumber) {
		this.agencyNumber = agencyNumber;
	}

	public BosList(int agencyNumber, String agencyName, Set<Agency> agencies) {
		this.agencyNumber = agencyNumber;
		this.agencyName = agencyName;
		this.agencies = agencies;
	}

	public int getAgencyNumber() {
		return this.agencyNumber;
	}

	public void setAgencyNumber(int agencyNumber) {
		this.agencyNumber = agencyNumber;
	}

	public String getAgencyName() {
		return this.agencyName;
	}

	public void setAgencyName(String agencyName) {
		this.agencyName = agencyName;
	}

	public Set<Agency> getAgencies() {
		return this.agencies;
	}

	public void setAgencies(Set<Agency> agencies) {
		this.agencies = agencies;
	}

}
