package au.gov.nsw.records.digitalarchive.ORM;
// default package
// Generated 31/07/2012 1:57:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Keyword generated by hbm2java
 */
public class Keyword implements java.io.Serializable {

	private Integer keywordId;
	private String keyword;
	private Set<KeywordPublication> keywordPublications = new HashSet<KeywordPublication>(
			0);

	public Keyword() {
	}

	public Keyword(String keyword, Set<KeywordPublication> keywordPublications) {
		this.keyword = keyword;
		this.keywordPublications = keywordPublications;
	}

	public Integer getKeywordId() {
		return this.keywordId;
	}

	public void setKeywordId(Integer keywordId) {
		this.keywordId = keywordId;
	}

	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public Set<KeywordPublication> getKeywordPublications() {
		return this.keywordPublications;
	}

	public void setKeywordPublications(
			Set<KeywordPublication> keywordPublications) {
		this.keywordPublications = keywordPublications;
	}

}
