package au.gov.nsw.records.digitalarchive.ORM;
// default package
// Generated 02/01/2013 11:00:11 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Member generated by hbm2java
 */
public class Member implements java.io.Serializable {

	private Integer memberId;
	private FullAgencyList fullAgencyList;
	private String firstname;
	private String lastname;
	private String email;
	private String phone;
	private String login;
	private String password;
	private Date registrationDate;
	private Date lastLogin;
	private Integer loginTimes;
	private String activated;
	private String privileged;
	private Date lastReset;
	private Set<Publication> publications = new HashSet<Publication>(0);

	public Member() {
	}

	public Member(FullAgencyList fullAgencyList, String firstname,
			String lastname, String email, String phone, String login,
			String password, Date registrationDate, Date lastLogin,
			Integer loginTimes, String activated, String privileged,
			Date lastReset, Set<Publication> publications) {
		this.fullAgencyList = fullAgencyList;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.phone = phone;
		this.login = login;
		this.password = password;
		this.registrationDate = registrationDate;
		this.lastLogin = lastLogin;
		this.loginTimes = loginTimes;
		this.activated = activated;
		this.privileged = privileged;
		this.lastReset = lastReset;
		this.publications = publications;
	}

	public Integer getMemberId() {
		return this.memberId;
	}

	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	public FullAgencyList getFullAgencyList() {
		return this.fullAgencyList;
	}

	public void setFullAgencyList(FullAgencyList fullAgencyList) {
		this.fullAgencyList = fullAgencyList;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getRegistrationDate() {
		return this.registrationDate;
	}

	public void setRegistrationDate(Date registrationDate) {
		this.registrationDate = registrationDate;
	}

	public Date getLastLogin() {
		return this.lastLogin;
	}

	public void setLastLogin(Date lastLogin) {
		this.lastLogin = lastLogin;
	}

	public Integer getLoginTimes() {
		return this.loginTimes;
	}

	public void setLoginTimes(Integer loginTimes) {
		this.loginTimes = loginTimes;
	}

	public String getActivated() {
		return this.activated;
	}

	public void setActivated(String activated) {
		this.activated = activated;
	}

	public String getPrivileged() {
		return this.privileged;
	}

	public void setPrivileged(String privileged) {
		this.privileged = privileged;
	}

	public Date getLastReset() {
		return this.lastReset;
	}

	public void setLastReset(Date lastReset) {
		this.lastReset = lastReset;
	}

	public Set<Publication> getPublications() {
		return this.publications;
	}

	public void setPublications(Set<Publication> publications) {
		this.publications = publications;
	}

}
