package au.gov.nsw.records.digitalarchive.ORM;


/**
 * PublisherPublication generated by hbm2java
 */
public class PublisherPublication implements java.io.Serializable {

	private Integer publisherPublicationId;
	private Publication publication;
	private FullAgencyList fullAgencyList;

	public PublisherPublication() {
	}

	public PublisherPublication(Publication publication,
			FullAgencyList fullAgencyList) {
		this.publication = publication;
		this.fullAgencyList = fullAgencyList;
	}

	public Integer getPublisherPublicationId() {
		return this.publisherPublicationId;
	}

	public void setPublisherPublicationId(Integer publisherPublicationId) {
		this.publisherPublicationId = publisherPublicationId;
	}

	public Publication getPublication() {
		return this.publication;
	}

	public void setPublication(Publication publication) {
		this.publication = publication;
	}

	public FullAgencyList getFullAgencyList() {
		return this.fullAgencyList;
	}

	public void setFullAgencyList(FullAgencyList fullAgencyList) {
		this.fullAgencyList = fullAgencyList;
	}

}
