package au.gov.nsw.records.digitalarchive.ORM;
// default package
// Generated 19/07/2012 9:38:43 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Archivist generated by hbm2java
 */
public class Archivist implements java.io.Serializable {

	private Integer archivistId;
	private Integer archivistType;
	private String firstname;
	private String lastname;
	private String email;
	private String employeeNumber;
	private String loginName;
	private String loginPassword;
	private Date lastLogin;
	private Integer loginTimes;
	private Set<Publication> publications = new HashSet<Publication>(0);

	public Archivist() {
	}

	public Archivist(Integer archivistType, String firstname, String lastname,
			String email, String employeeNumber, String loginName,
			String loginPassword, Date lastLogin, Integer loginTimes,
			Set<Publication> publications) {
		this.archivistType = archivistType;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.employeeNumber = employeeNumber;
		this.loginName = loginName;
		this.loginPassword = loginPassword;
		this.lastLogin = lastLogin;
		this.loginTimes = loginTimes;
		this.publications = publications;
	}

	public Integer getArchivistId() {
		return this.archivistId;
	}

	public void setArchivistId(Integer archivistId) {
		this.archivistId = archivistId;
	}

	public Integer getArchivistType() {
		return this.archivistType;
	}

	public void setArchivistType(Integer archivistType) {
		this.archivistType = archivistType;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getEmployeeNumber() {
		return this.employeeNumber;
	}

	public void setEmployeeNumber(String employeeNumber) {
		this.employeeNumber = employeeNumber;
	}

	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	public String getLoginPassword() {
		return this.loginPassword;
	}

	public void setLoginPassword(String loginPassword) {
		this.loginPassword = loginPassword;
	}

	public Date getLastLogin() {
		return this.lastLogin;
	}

	public void setLastLogin(Date lastLogin) {
		this.lastLogin = lastLogin;
	}

	public Integer getLoginTimes() {
		return this.loginTimes;
	}

	public void setLoginTimes(Integer loginTimes) {
		this.loginTimes = loginTimes;
	}

	public Set<Publication> getPublications() {
		return this.publications;
	}

	public void setPublications(Set<Publication> publications) {
		this.publications = publications;
	}

}
