package au.gov.nsw.records.digitalarchive.ORM;


import java.util.Date;

/**
 * UploadedFile generated by hbm2java
 */
public class UploadedFile implements java.io.Serializable {

	private Integer fileId;
	private Publication publication;
	private String fileName;
	private String downloadLink;
	private String uploadedTo;
	private String contentType;
	private String size;
	private String pages;
	private Date dateUploaded;
	private String uploadedBy;
	private String ipAddress;

	public UploadedFile() {
	}

	public UploadedFile(Publication publication, String fileName,
			String downloadLink, String uploadedTo, String contentType,
			String size, String pages, Date dateUploaded, String uploadedBy,
			String ipAddress) {
		this.publication = publication;
		this.fileName = fileName;
		this.downloadLink = downloadLink;
		this.uploadedTo = uploadedTo;
		this.contentType = contentType;
		this.size = size;
		this.pages = pages;
		this.dateUploaded = dateUploaded;
		this.uploadedBy = uploadedBy;
		this.ipAddress = ipAddress;
	}

	public Integer getFileId() {
		return this.fileId;
	}

	public void setFileId(Integer fileId) {
		this.fileId = fileId;
	}

	public Publication getPublication() {
		return this.publication;
	}

	public void setPublication(Publication publication) {
		this.publication = publication;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getDownloadLink() {
		return this.downloadLink;
	}

	public void setDownloadLink(String downloadLink) {
		this.downloadLink = downloadLink;
	}

	public String getUploadedTo() {
		return this.uploadedTo;
	}

	public void setUploadedTo(String uploadedTo) {
		this.uploadedTo = uploadedTo;
	}

	public String getContentType() {
		return this.contentType;
	}

	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	public String getSize() {
		return this.size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	public String getPages() {
		return this.pages;
	}

	public void setPages(String pages) {
		this.pages = pages;
	}

	public Date getDateUploaded() {
		return this.dateUploaded;
	}

	public void setDateUploaded(Date dateUploaded) {
		this.dateUploaded = dateUploaded;
	}

	public String getUploadedBy() {
		return this.uploadedBy;
	}

	public void setUploadedBy(String uploadedBy) {
		this.uploadedBy = uploadedBy;
	}

	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

}
